# Generated by Django 3.2.4 on 2024-04-18 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='scheduled_week_day',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_time',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_week_day', models.CharField(max_length=30)),
                ('session_time', models.TimeField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseload.child')),
            ],
        ),
    ]
