# Generated by Django 3.2.4 on 2024-04-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseload', '0002_auto_20240418_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_id',
        ),
    ]
