# Generated by Django 4.2.11 on 2024-04-28 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseload', '0003_remove_session_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('sessions_completed', models.IntegerField()),
                ('excused_absence', models.IntegerField()),
                ('unexcused_absence', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseload.child')),
            ],
        ),
    ]
